pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-libreoffice .
    when:
      branch: master
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-libreoffice quay.io/ukhomeofficedigital/hocs-libreoffice:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-libreoffice quay.io/ukhomeofficedigital/hocs-libreoffice:latest
      - docker push quay.io/ukhomeofficedigital/hocs-libreoffice:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-libreoffice:latest
    when:
      branch: master
      event: push